# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# create Azure openvpn security group rules
---
- name: OPENVPN OVERLAY AZURE | applying openvpn security rules
  azure_rm_securitygroup:
    resource_group: "{{ specified_resourcegroup.name }}"
    name: "dnsg_{{ project }}_ssh_public_external"
    rules:
      - name: AllowOpenVPN
        protocol: Udp
        source_address_prefix: '*'
        source_port_range: '*'
        destination_address_prefix: "{{ internal_public_subnet_result.properties.addressPrefix }}"
        destination_port_range: 1194
        access: Allow
        priority: 101
        direction: Inbound
  register: sg_openvpn
