# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# Apply AWS postgresql security group rules
---
- name: OPENVPN OVERLAY AWS | discovering {{ hostapplication }} instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": "{{ hostapplication }}"
      "tag:Cluster": "{{ cluster | default ('none') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: all_openvpn_nodes
  when: cloud == 'aws'

# construct list of all interfaces attached to postgresql nodes
- set_fact:
    openvpn_interfaces: "{{ all_openvpn_nodes.instances | map(attribute='network_interfaces') | list }}"
  when: all_openvpn_nodes.instances | length > 0
  
# apply postgresql rule
- name: OPENVPN OVERLAY AWS | applying {{ application }} security rules to interface 0
  ec2_eni:
    region: "{{ region }}"
    eni_id: "{{ item.network_interface_id }}"
    security_groups:
      - "{{ sg_openvpn.group_id }}"
  with_items: "{{ openvpn_interfaces }}"
  when: item.attachment.device_index == 0