# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# discover AWS inventory
---
- name: OPENVPN OVERLAY AWS | restricting to jumphost
  set_fact: hostapplication=jumphost
  
- name: OPENVPN OVERLAY AWS | discovering {{ hostapplication }}
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": "{{ hostapplication }}"
      "tag:Cluster": "{{ cluster | default ('none') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: openvpn_instances
  when: cloud == 'aws'
  
- name: OPENVPN OVERLAY AWS | building {{ application }} host group
  add_host: hostname="{{ item }}" groupname="{{ application }}" ansible_user="{{ user }}" ansible_ssh_private_key_file="{{ key_path | default("{{ playbook_dir }}") }}/{{ cloud }}-{{ region }}-{{ project }}-{{ hostapplication }}-{{ domain }}-private-key.pem"
  with_items: "{{ openvpn_instances.instances | map (attribute='public_ip_address') | list }}"
  when:
    - cloud == 'aws'
    - openvpn_instances is defined
    - openvpn_instances.instances|length > 0

- name: OPENVPN OVERLAY AWS | building {{ application }} host group
  add_host: hostname="{{ item }}" groupname="{{ application }}_private" ansible_user="{{ user }}" ansible_ssh_private_key_file="{{ key_path | default("{{ playbook_dir }}") }}/{{ cloud }}-{{ region }}-{{ project }}-{{ hostapplication }}-{{ domain }}-private-key.pem"
  with_items: "{{ openvpn_instances.instances | map (attribute='private_ip_address') | list }}"
  when:
    - cloud == 'aws'
    - openvpn_instances is defined
    - openvpn_instances.instances|length > 0
